function T = codec_payload_manifest()
%CODEC_PAYLOAD_MANIFEST What is actually retained after compression.
% Uses cell arrays of character vectors for broad MATLAB compatibility.
Algorithm = {'ASBC';'DWT-Hybrid';'CS-OMP';'MMC';'SVDCS'};
CorePayload = { ...
'Global F0,W,Rk,fs,block length,Sk,K,qstep,scale; harmonic/interharmonic activity masks; per-active-subband quantized complex downsampled baseband samples; interharmonic sparse FFT index/Re/Im/scale qe'; ...
'Wavelet/decomposition metadata N,L,wname,Book,qbits,delta; per-level quantizer scales; Huffman dictionaries+bitstreams for approximation/delta coefficients, detail values and run-length gaps; nonzero count'; ...
'Quantized measurement vector yq; measurement scale yscale; N,M,basis,random seed,K0,tolerance,ybits/RQ. Phi/Psi/A are not transmitted and are regenerated from basis+seed'; ...
'Per window: model identifier/family/order/eta/factor, normalization exponent kx, quantized model parameters/indices and bit allocation; residual method none/DCT/DWT, residual exponent kr, sparse transform coefficient indices and signed quantized values, header fields'; ...
'Synchronized-cycle metadata Nppc/Nframes/fftStep/scale; spectral-variation MC runs (q,SUM,CNT), then LZW payload plus code count. Paper-level deployment payload is LZW(MC), not the full MATLAB debug struct'};
DecoderState = { ...
'Codec parameters plus current block reconstruction buffers'; ...
'Wavelet metadata/quantizer scales/Huffman codebooks during decode'; ...
'Regenerated sensing/basis matrices (current MATLAB implementation) and OMP support/residual state'; ...
'Two previous reconstructed windows and previous selected model/quantized parameters for predictive models'; ...
'Reconstruction run position per q; FFT/IFFT buffers; LZW dictionary/state'};
MatlabOnlyOrRedundant = { ...
'Cell/struct container overhead and some derived metadata are MATLAB implementation artifacts'; ...
'MATLAB cell dictionaries/arrays are larger than a packed embedded bitstream'; ...
'Encoder computes s_hat/x_hat for diagnostics although they need not be part of an edge encoder'; ...
'Current packet carries theta_q plus model centers/widths and residual.rhat for convenience; a packed deployment stream can omit derived/reconstructed fields'; ...
'Current packet retains both decoded MC and compressed payload for verification; deployed storage should retain the compressed payload and minimum metadata only'};
T = table(Algorithm,CorePayload,DecoderState,MatlabOnlyOrRedundant);
end
