function rhat = mmc_decode_residual(residual, cfg)
%MMC_DECODE_RESIDUAL Decode residual payload generated by mmc_encode_residual.
if strcmpi(residual.name,'none') || residual.nbits==0
    rhat=zeros(cfg.N,1); return;
end
p=residual.payload;
qmax=2^(p.value_bits-1)-1;
cn=zeros(cfg.N,1);
cn(p.indices)=p.q/qmax;
c=cn*2^(residual.kr);

switch upper(residual.transform)
    case 'DCT'
        T=dct_matrix(cfg.N); rhat=T'*c;
    case 'DWT'
        rhat=haar_inverse(c);
    otherwise
        error('Unknown residual transform.');
end
end

function T=dct_matrix(N)
persistent cacheN cacheT
if isempty(cacheN)||cacheN~=N
    T=zeros(N,N);
    for k=0:N-1
        a=sqrt(2/N); if k==0,a=sqrt(1/N);end
        T(k+1,:)=a*cos(pi*(0.5+(0:N-1))*k/N);
    end
    cacheN=N;cacheT=T;
else,T=cacheT;end
end

function x=haar_inverse(c)
c=c(:);N=numel(c);a=c(1);pos=2;len=1;
while len<N
    d=c(pos:pos+len-1);pos=pos+len;
    temp=zeros(2*len,1);
    temp(1:2:end)=(a+d)/sqrt(2);
    temp(2:2:end)=(a-d)/sqrt(2);
    a=temp;len=2*len;
end
x=a;
end
